# Generated by Django 6.0.1 on 2026-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Campus Admin'), ('KITCHEN_STAFF', 'Kitchen Staff'), ('WARDEN', 'Hostel Warden'), ('RECIPIENT_ORG', 'Recipient Organization'), ('ESG_LEAD', 'Sustainability & ESG Lead')], default='KITCHEN_STAFF', max_length=20),
        ),
    ]
