# Generated by Django 6.0.1 on 2026-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_exam_period', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Diwali break', 'Mid-sem exams'", max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage_hours', models.PositiveIntegerField(default=4, help_text="Max hours food can sit before it's unsafe to redistribute")),
                ('min_storage_temp_celsius', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('max_storage_temp_celsius', models.DecimalField(decimal_places=1, default=60.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
