# Generated by Django 6.0.1 on 2026-08-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MAIN', 'Main Course'), ('SIDE', 'Side Dish'), ('BEVERAGE', 'Beverage'), ('DESSERT', 'Dessert')], max_length=20)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, help_text='Cost in ₹ per kg, used for savings calc', max_digits=8)),
                ('carbon_factor_kg_co2e_per_kg', models.DecimalField(decimal_places=3, default=0, help_text='kg CO2e emitted per kg of this food item, used for carbon savings calc', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MealConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_prepared_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_consumed_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('headcount', models.PositiveIntegerField(help_text='Number of people served this session')),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_exam_period', models.BooleanField(default=False)),
                ('weather_note', models.CharField(blank=True, help_text="e.g. 'rainy', 'heatwave' — optional for now", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='meals.mealsession')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='meals.menuitem')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'session', 'item')},
            },
        ),
    ]
