# Generated by Django 6.0.1 on 2026-08-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0001_initial'),
        ('pickups', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactrecord',
            name='pickup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_record', to='pickups.pickup'),
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_records', to='recipients.recipient'),
        ),
    ]
