# Generated by Django 6.0.1 on 2026-08-18 12:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('risk_category', models.CharField(choices=[('LOW', 'Low risk (dry / shelf-stable)'), ('MEDIUM', 'Medium risk (cooked, low moisture)'), ('HIGH', 'High risk / TCS food (dairy, meat, rice, gravies)')], default='HIGH', max_length=10)),
                ('max_hold_minutes_danger_zone', models.PositiveIntegerField(default=240, help_text="Max cumulative minutes food may spend between 5C-60C before it's unsafe.")),
                ('max_hold_minutes_cold', models.PositiveIntegerField(default=1440, help_text='Max minutes safe when held at or below 5C (refrigerated).')),
                ('max_hold_minutes_hot', models.PositiveIntegerField(default=240, help_text='Max minutes safe when held at or above 60C (hot holding).')),
                ('danger_zone_min_c', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('danger_zone_max_c', models.DecimalField(decimal_places=1, default=60.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('LITRE', 'Litres'), ('PORTION', 'Portions / servings')], default='KG', max_length=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('prepared_at', models.DateTimeField(help_text='Time food was cooked / prepared.')),
                ('storage_location', models.CharField(blank=True, max_length=150)),
                ('current_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_refrigerated', models.BooleanField(default=False)),
                ('is_hot_held', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved for pickup'), ('PICKED_UP', 'Picked up'), ('EXPIRED', 'Expired / unsafe'), ('DISCARDED', 'Discarded')], default='AVAILABLE', max_length=12)),
                ('safe_until', models.DateTimeField(help_text='Timestamp after which the food must not be redistributed.')),
                ('danger_zone_minutes_elapsed', models.PositiveIntegerField(default=0)),
                ('estimated_cost_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_co2e_saved_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discarded_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_created', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surplus_entries', to='meals.mealconsumptionlog')),
                ('safety_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surplus_entries', to='surplus.foodsafetyrule')),
            ],
            options={
                'ordering': ['safe_until'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('surplus_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='surplus.surplusfood')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='surplusfood',
            index=models.Index(fields=['status', 'safe_until'], name='surplus_sur_status_9b20a6_idx'),
        ),
    ]
