# Generated by Django 6.0.1 on 2026-08-18 12:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(help_text='Matching score used to rank recipient eligibility.')),
                ('was_selected', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In transit'), ('COMPLETED', 'Completed'), ('REJECTED_UNSAFE', 'Rejected - unsafe'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=8)),
                ('safety_check_passed', models.BooleanField(blank=True, null=True)),
                ('temperature_at_pickup_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_handled', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='recipients.recipient')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
