# Generated by Django 6.0.1 on 2026-08-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickups', '0001_initial'),
        ('recipients', '0001_initial'),
        ('surplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='surplus_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='surplus.surplusfood'),
        ),
        migrations.AddField(
            model_name='pickupmatchlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='recipients.recipient'),
        ),
        migrations.AddField(
            model_name='pickupmatchlog',
            name='surplus_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='surplus.surplusfood'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['status', 'scheduled_time'], name='pickups_pic_status_e11d51_idx'),
        ),
    ]
