# Generated by Django 6.0.1 on 2026-08-18 12:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity_quantity', models.DecimalField(decimal_places=2, help_text='Max quantity this recipient can accept per pickup/day, in `capacity_unit`.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_unit', models.CharField(choices=[('KG', 'Kilograms'), ('LITRE', 'Litres'), ('PORTION', 'Portions / servings')], default='KG', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Recipient opts out of matching (e.g. temporarily full) without losing account access.')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'RECIPIENT_ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='recipients__is_acti_2fe139_idx')],
            },
        ),
    ]
